# Basic windows ci workflow for model zoo.
# Runs model checker for models updated in the PR

name: Windows CI

# Triggers the workflow on push or pull request events but only for the main branch
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest
    strategy:
      matrix:
        python-version: [3.8]
        architecture: ['x64']

    steps:
      - uses: actions/checkout@v2
        name: Checkout repo
        
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}
          architecture: ${{ matrix.architecture }}
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # TODO: now ONNX only supports Protobuf <= 3.20.1
          python -m pip install protobuf==3.20.1
          python -m pip install onnx onnxruntime requests py-cpuinfo
          python -m cpuinfo

      - name: Test new models by onnx
        run: |
          python workflow_scripts/test_models.py --target onnx --drop

      - name: Test new models by onnxruntime
        run: |
          python workflow_scripts/test_models.py --target onnxruntime --drop
